### PR TITLE
Lib_exec_replacement for update functions

### PR DESCRIPTION
**Pull request by abenkovskii**
1. It runs
2. I didn't test it enough yet
3. performance comparison soon (tm)
4. It's in a raw state. I managed to rout values to where I need but I don't like how it turned out and will probably reroute them later.
   issue: #23

### CODE REVIEW

**Comment by akrasuski1** [comment]
`else if update_index=1{global __akros_update_result__ is update_window_manager(process).}`

so you hardcode functions somewhere. Exactly what I wanted to avoid through the update function mechanics. How is this better than simply adding in process update loop: `if process.name="Vessel stats" { some_update_function ().` ? (pseudocode). i don't see advantages of your approach, could you explain why is this PR useful?

**Comment by akrasuski1** [comment]
ok, turns out that I shouldn't look at github while on mobile. I haven't seen all the files, hence the above comment. Sorry. I'll make a proper response when I'm home.

**Comment by abenkovskii** [comment]
Sorry. I forgot to delete (or .gitignor) **akros_update_cache**.ks. The system generates it here: https://github.com/akrasuski1/akrOS/pull/46/files#diff-c770b4abdfd6a2eaece1f69d1090e5d0R162 when you register an update function.

**Comment by akrasuski1** [comment]
Ok, I have read all the commits now and understand the idea behind this PR. 

The basic idea seems to be ok - it solves the issue of constant recompilation in the `lib_exec` file. I wonder however, if the changes should not go into the `lib_exec` itself. You know, this whole PR is concentrated on working around kOS limitations (no function pointers). And that is one of the things `lib_exec` was made for. When function pointers come, akrOS will not need these workarounds, so I'd rather not sprinkle the code with such things, if possible, because it will require the same amount of work later to remove it. A much better idea would be to add a similar functionability to `lib_exec` or some other library (`lib_exec_cached` or something) with function like `evaluate_function`, but which would keep internal list with history of already used function strings. If it's new, register the function as in `register_update_function`, otherwise use cached version. What do you say?

**Comment by abenkovskii** [comment]
> which would keep internal list with history of already used function strings

I understand what you are talking about and it's probably possible but it will be a lot more complicated than the current lib_exec implementation. I don't think it worth the time and effort required. Function pointers are coming soon (likely in next update or update after it).

**Comment by akrasuski1** [comment]
I see. And probably you are right that it is not worth the hassle. But coming to the original topic - I appreciate your work, but for the reasons I mentioned earlier (polluting akrOS with workarounds for short/medium-term kOS bugs) I don't feel it's a good idea to merge this PR. In other words: for now, we can cope with frequent recompilation (especially that akrOS is not released to public yet).

**Comment by abenkovskii** [comment]
> (especially that kOS is not realeased to public yet).

Do you mean akrOS?

**Comment by akrasuski1** [comment]
Yeah, I fixed the mistake.

**Comment by abenkovskii** [comment]
Closing this request than.

**Pull request closed without merging**
